# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# Block Designs: bd/ZYNQ/ZYNQ.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ZYNQ || ORIG_REF_NAME==ZYNQ} -quiet] -quiet

# IP: bd/ZYNQ/ip/ZYNQ_processing_system7_0_0/ZYNQ_processing_system7_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ZYNQ_processing_system7_0_0 || ORIG_REF_NAME==ZYNQ_processing_system7_0_0} -quiet] -quiet

# IP: bd/ZYNQ/ip/ZYNQ_axi_gpio_0_3/ZYNQ_axi_gpio_0_3.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ZYNQ_axi_gpio_0_3 || ORIG_REF_NAME==ZYNQ_axi_gpio_0_3} -quiet] -quiet

# IP: bd/ZYNQ/ip/ZYNQ_axi_gpio_1_0/ZYNQ_axi_gpio_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ZYNQ_axi_gpio_1_0 || ORIG_REF_NAME==ZYNQ_axi_gpio_1_0} -quiet] -quiet

# IP: bd/ZYNQ/ip/ZYNQ_axi_gpio_2_0/ZYNQ_axi_gpio_2_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ZYNQ_axi_gpio_2_0 || ORIG_REF_NAME==ZYNQ_axi_gpio_2_0} -quiet] -quiet

# IP: bd/ZYNQ/ip/ZYNQ_axi_bram_ctrl_0_0/ZYNQ_axi_bram_ctrl_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ZYNQ_axi_bram_ctrl_0_0 || ORIG_REF_NAME==ZYNQ_axi_bram_ctrl_0_0} -quiet] -quiet

# IP: bd/ZYNQ/ip/ZYNQ_axi_bram_ctrl_0_bram_0/ZYNQ_axi_bram_ctrl_0_bram_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ZYNQ_axi_bram_ctrl_0_bram_0 || ORIG_REF_NAME==ZYNQ_axi_bram_ctrl_0_bram_0} -quiet] -quiet

# IP: bd/ZYNQ/ip/ZYNQ_axi_smc_0/ZYNQ_axi_smc_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ZYNQ_axi_smc_0 || ORIG_REF_NAME==ZYNQ_axi_smc_0} -quiet] -quiet

# IP: bd/ZYNQ/ip/ZYNQ_rst_ps7_0_100M_0/ZYNQ_rst_ps7_0_100M_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ZYNQ_rst_ps7_0_100M_0 || ORIG_REF_NAME==ZYNQ_rst_ps7_0_100M_0} -quiet] -quiet

# XDC: c:/Users/moman/OneDrive/Documents/Education/etudeAcademique/TP3/TP3.gen/sources_1/bd/ZYNQ/ZYNQ_ooc.xdc
