# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# Block Designs: bd/led/led.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==led || ORIG_REF_NAME==led} -quiet] -quiet

# IP: bd/led/ip/led_processing_system7_0_0/led_processing_system7_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==led_processing_system7_0_0 || ORIG_REF_NAME==led_processing_system7_0_0} -quiet] -quiet

# IP: bd/led/ip/led_axi_gpio_0_0/led_axi_gpio_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==led_axi_gpio_0_0 || ORIG_REF_NAME==led_axi_gpio_0_0} -quiet] -quiet

# IP: bd/led/ip/led_auto_pc_0/led_auto_pc_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==led_auto_pc_0 || ORIG_REF_NAME==led_auto_pc_0} -quiet] -quiet

# IP: bd/led/ip/led_ps7_0_axi_periph_0/led_ps7_0_axi_periph_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==led_ps7_0_axi_periph_0 || ORIG_REF_NAME==led_ps7_0_axi_periph_0} -quiet] -quiet

# IP: bd/led/ip/led_rst_ps7_0_100M_0/led_rst_ps7_0_100M_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==led_rst_ps7_0_100M_0 || ORIG_REF_NAME==led_rst_ps7_0_100M_0} -quiet] -quiet

# XDC: c:/Users/moman/OneDrive/Documents/Education/etudeAcademique/led_project/led_project.gen/sources_1/bd/led/led_ooc.xdc
